version: '3.2'

services:
  db:
    image: docker.io/mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: "social_db"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always
    ports:
      - "3306:3306"