logging:
  level:
    root: ERROR
    # Set DEBUG level to activate our log-filter to log each request and response
    org.springframework.web.filter.CommonsRequestLoggingFilter: ERROR

spring:
  social:
    facebook:
      app-id: 1585553454895569
      app-secret: d81f7a6aab51c0d3e9543487fa956d60
    twitter:
      app-id: dWQnQEHz8rA2OHs0Ns96hLSZQ
      app-secret: hJrjc2lplhwLimdb6YAe2jvRVTwzNqvKx02hbkzilklIpXgqJd

spring.datasource:
      url: jdbc:mysql://thematrix.localhost:3306/social_db?useSSL=false
      username: test
      password: test
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: passw0rd
    key-password: passw0rd
    key-store-type: JKS